### ISSUE TITLE
How are changes within a slice handled?

### ISSUE THREAD

**Issue by kfarr** [d-wasserman/shared-row#10]
How to handle a shared row slice format when there are changes to a slice type within the street?

Some examples:
- a vehicle through lane turns into a right-turn-only lane
- lane width changes or merging (parking transitions to a larger sidewalk)
- a flex zone in a given street has all 3 of: bench, bus stop, bike share station

Or are changes to the slice beyond the scope of a slice and instead a new set of slices should be created?

**Comment by d-wasserman** [comment]
The spec is written in a way that there are some accommodations for mid-slice changes or attributes, but ultimately it might be a matter of appropriate segmentation when that level of detail is necessary. We are happy to take any suggestions or a PR on how to manage this, but given that the nature of the street and the use of the spec could be used a few ways we are facing similar issues that GTFS does regarding flexibility and over specification. At this time we might suggest increasing the number of segments, but there is room to modify the slice specification for common needs (lane transitions). 

@louh  do you have any thoughts on this?

**Comment by d-wasserman** [comment]
I think for right now, I am going to call this issue closed. I think for right now, the idea would be to have sections change at the mid point of a transition to the desired new cross-section for those detailed segments.
