### ISSUE TITLE
Express Shared-Row.xlsx in a text format

### ISSUE THREAD

**Issue by dabreegster** [d-wasserman/shared-row#6]
I don't have Excel, so I'm using Google Sheets to view [Shared-Row.xlsx](https://drive.google.com/file/d/1wv4aTJWzB6XwodfNeJixDqxSkpSkxMI0/view?usp=sharing). It'd be much easier to view and edit this spec in a text format. Some ideas:

1) Markdown tables. The rows would be really wide with the description, though.

2) Some formal schema, like https://json-schema.org/

3) Markdown using lists. An example:

### Automotive (dedicated)

"Dedicated" means "primarily intended for." In each of these cases mixed traffic may be permitted and a meta tag will indicate what kind of mixing is allowed.

- `drive_lane`: This denotes a through-lane intended for automobile traffic. 
  - `sharrow` (optional boolean): Describes whether a drive_lane slice has a sharrow stamp located within it. 
- `turn_lane`: A lane where automobiles are taken out of traffic flow in order to queue for turning. These lanes are considered to be center-running and can be bidirectional if they represent a block to block segment with end and begin depths for symmetrical intersection end points (no additional turn lanes on either end of the segment). Segments should be split if one block has varying turn lanes counts. 
  - `sharrow` (optional boolean): A turn_lane may have a sharrow stamp
  - `end_depth` (conditionally required number): This specifies the turn lane depth for the end point of the existing segment. If blank, it is assumed the turn lane is the depth of the entire length of the represented segment. For block to block representations, this parameter is required, and only works for symmetrical end points of intersections.

**Comment by d-wasserman** [comment]
These are good ideas. I think the quick fix is the markdown table. Long term, something like the JSON schema would be a great idea.  If the table is too unwieldy, the example of Markdown lists is a good one.

**Comment by dabreegster** [comment]
Stumbled across https://github.com/zephyr-data-specs/GMNS/blob/updates/Specification/Signals.md, which is a detailed spec in .md

**Comment by d-wasserman** [comment]
I recently edited the main page to add this project and MIRE as a related database & specification. I think I would be open to deferring to GMNS for intersections.

**Comment by d-wasserman** [comment]
@dabreegster , I recently added markdown tables to the specification pages and outlined multiple ways to review the specification in the [specification sheet](https://github.com/d-wasserman/shared-row/tree/master/specification). Let me know if you have any additional suggestions.

**Comment by dabreegster** [comment]
This is great, thanks!
