### ISSUE TITLE
Confusing terminology: crosswalks

### ISSUE THREAD

**Issue by dabreegster** [d-wasserman/shared-row#7]
The spec appears to be using the term "crosswalk" to refer to a way of representing slices in the flattened additive format:

> A share-row-crosswalk consists of each row representing a slice of a shared-street id. Intended to allow the conversion between Additive and Sliced based specifications in an editable GIS/SQL database.

The word "crosswalk" is synonymous with [pedestrian crossings](https://en.wikipedia.org/wiki/Pedestrian_crossing). I'm very confused by the crosswalk tab in the schema, because it doesn't seem to have anything to do with pedestrian crossings. Should this be renamed?

**Comment by d-wasserman** [comment]
Per our offline conversation, @dabreegster: 
Agreed. I took the terminology from the [Census actually.](https://www.nhgis.org/user-resources/geographic-crosswalks) That said, that is just one type of word for correspondence or intermediate data format. We can think of giving it a different type of intermediate name. 

Tangentially related, there is also an issue thinking about an intersection specification all together. https://github.com/d-wasserman/shared-row/issues/4

**Comment by d-wasserman** [comment]
As an intermediate measure, I made it clear this serves as a [schema crosswalk ](https://en.wikipedia.org/wiki/Schema_crosswalk) in the sheet and the samples.
